/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./src/components/table/Demo.vue')['default']
    Demo2: typeof import('./src/components/table/Demo2.vue')['default']
    EditableCell: typeof import('./src/components/table/components/editable-cell/EditableCell.vue')['default']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptions: typeof import('element-plus/es')['ElOptions']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FormTable: typeof import('./src/components/table/FormTable.vue')['default']
  }
}
